// Code generated by "stringer -type=ScopeKind"; DO NOT EDIT.

package check

import "strconv"

const _ScopeKind_name = "ScopeUniversalScopePreludeScopeScriptScopeFunctionScopeBlock"

var _ScopeKind_index = [...]uint8{0, 14, 26, 37, 50, 60}

func (i ScopeKind) String() string {
	if i >= ScopeKind(len(_ScopeKind_index)-1) {
		return "ScopeKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ScopeKind_name[_ScopeKind_index[i]:_ScopeKind_index[i+1]]
}
