// Code generated by "stringer -type=CallKind"; DO NOT EDIT.

package ast

import "strconv"

const _CallKind_name = "CallFunctionCallMethodCallNew"

var _CallKind_index = [...]uint8{0, 12, 22, 29}

func (i CallKind) String() string {
	if i >= CallKind(len(_CallKind_index)-1) {
		return "CallKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CallKind_name[_CallKind_index[i]:_CallKind_index[i+1]]
}
