// Code generated by "stringer -type=LiteralKind"; DO NOT EDIT.

package ast

import "strconv"

const _LiteralKind_name = "BadLiteralLitBoolLitNullLitRegexLitStringLitIntLitDecimal"

var _LiteralKind_index = [...]uint8{0, 10, 17, 24, 32, 41, 47, 57}

func (i LiteralKind) String() string {
	if i >= LiteralKind(len(_LiteralKind_index)-1) {
		return "LiteralKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LiteralKind_name[_LiteralKind_index[i]:_LiteralKind_index[i+1]]
}
