// Code generated by "stringer -type=LoopKind -linecomment=true"; DO NOT EDIT.

package ast

import "strconv"

const _LoopKind_name = "<unknown loop kind>forwhiledo-whileeachin-each"

var _LoopKind_index = [...]uint8{0, 19, 22, 27, 35, 39, 46}

func (i LoopKind) String() string {
	if i >= LoopKind(len(_LoopKind_index)-1) {
		return "LoopKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LoopKind_name[_LoopKind_index[i]:_LoopKind_index[i+1]]
}
