// Code generated by "stringer -type=OpKind"; DO NOT EDIT.

package ast

import "strconv"

const (
	_OpKind_name_0 = "OpBad"
	_OpKind_name_1 = "OpMulOpDivOpRemOpAddOpSubOpIncOpDecOpPosOpNeg"
	_OpKind_name_2 = "OpFindOpMatch"
	_OpKind_name_3 = "OpLSHOpRSHOpUSHOpBitsAndOpBitsXOROpBitsOROpBitsNot"
	_OpKind_name_4 = "OpANDOpOROpBoolNot"
	_OpKind_name_5 = "OpCmpEQOpCmpEQROpCmpNEOpCmpNEROpCmpLTOpCmpLTEOpCmpGTOpCmpGTE"
	_OpKind_name_6 = "OpAssignOpInstanceOf"
)

var (
	_OpKind_index_1 = [...]uint8{0, 5, 10, 15, 20, 25, 30, 35, 40, 45}
	_OpKind_index_2 = [...]uint8{0, 6, 13}
	_OpKind_index_3 = [...]uint8{0, 5, 10, 15, 24, 33, 41, 50}
	_OpKind_index_4 = [...]uint8{0, 5, 9, 18}
	_OpKind_index_5 = [...]uint8{0, 7, 15, 22, 30, 37, 45, 52, 60}
	_OpKind_index_6 = [...]uint8{0, 8, 20}
)

func (i OpKind) String() string {
	switch {
	case i == 0:
		return _OpKind_name_0
	case 263 <= i && i <= 271:
		i -= 263
		return _OpKind_name_1[_OpKind_index_1[i]:_OpKind_index_1[i+1]]
	case 528 <= i && i <= 529:
		i -= 528
		return _OpKind_name_2[_OpKind_index_2[i]:_OpKind_index_2[i+1]]
	case 786 <= i && i <= 792:
		i -= 786
		return _OpKind_name_3[_OpKind_index_3[i]:_OpKind_index_3[i+1]]
	case 1049 <= i && i <= 1051:
		i -= 1049
		return _OpKind_name_4[_OpKind_index_4[i]:_OpKind_index_4[i+1]]
	case 1308 <= i && i <= 1315:
		i -= 1308
		return _OpKind_name_5[_OpKind_index_5[i]:_OpKind_index_5[i+1]]
	case 1572 <= i && i <= 1573:
		i -= 1572
		return _OpKind_name_6[_OpKind_index_6[i]:_OpKind_index_6[i+1]]
	default:
		return "OpKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
